### ISSUE TITLE
InlineBallutes

### ISSUE THREAD

**Issue by qm3ster** [KSP-CKAN/NetKAN#2386]
```
{
    "spec_version" : "v1.4",
    "identifier"   : "InlineBallutes",
    "$kref"        : "#/ckan/kerbalstuff/1166",
    "x_netkan_license_ok": true,
    "install" : [
        {
            "find"       : "KermangeddonIndustries",
            "install_to" : "GameData"
        }
    ]
}
```
Apparently it doesn't like something that comes back from https://kerbalstuff.com/api/mod/1166?

```
netkan --debug --verbose netkan\InlineBallutes.netkan
66 [1] INFO CKAN.NetKAN.Program (null) - Transforming netkan\InlineBallutes.netkan
103 [1] INFO CKAN.NetKAN.Program (null) - Using CKAN cache at C:/SteamLibrary/SteamApps/common/Kerbal Space Program/CKAN/downloads
147 [1] INFO CKAN.NetKAN.Program (null) - Finished reading input
149 [1] INFO CKAN.NetKAN.Validators.HasIdentifierValidator (null) - Validating that metadata contains an identifier
149 [1] INFO CKAN.NetKAN.Program (null) - Input successfully passed pre-validation
159 [1] INFO CKAN.NetKAN.Transformers.KerbalstuffTransformer (null) - Executing KerbalStuff transformation with #/kerbalstuff/1166
1674 [1] INFO CKAN.NetKAN.Transformers.KerbalstuffTransformer (null) - Found KerbalStuff Mod: Inline Ballutes 1.2.1
1710 [1] INFO CKAN.NetKAN.Transformers.DownloadSizeTransformer (null) - Executing Download Size transformation with #/kerbalstuff/1166
1711 [1] INFO CKAN.NetKAN.Transformers.GeneratedByTransformer (null) - Executing Generated By transformation with #/kerbalstuff/1166
1712 [1] INFO CKAN.NetKAN.Transformers.StripNetkanMetadataTransformer (null) - Executing Strip Netkan Metadata transformation with #/kerbalstuff/1166
1720 [1] INFO CKAN.NetKAN.Transformers.PropertySortTransformer (null) - Executing property sort transformation
1725 [1] INFO CKAN.NetKAN.Program (null) - Finished transformation
1765 [1] FATAL CKAN.NetKAN.Program (null) - Exception has been thrown by the target of an invocation.
1767 [1] FATAL CKAN.NetKAN.Program (null) -    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at CKAN.JsonSimpleStringConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at CKAN.JsonSingleOrArrayConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at CKAN.CkanModule.FromJson(String json)
   at CKAN.NetKAN.Validators.CkanValidator.Validate(Metadata metadata)
   at CKAN.NetKAN.Program.Main(String[] args)
```

**Comment by qm3ster** [comment]
It was a license that was missing hyphens. I added the correct spelling of the license to the netkan.
