### ISSUE TITLE
Crash when updating mods.

### ISSUE THREAD

**Issue by Wolfyharvell** [KSP-CKAN/NetKAN#4783]
This crash seems to appear when I update any mod at all. This happens on 2 separate computers, both are running 64-bit Windows 10.

Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\Harvell\AppData\Local\Temp\tmp728C.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncModulesDownloader.<DownloadModules>c__AnonStorey0.<>m__0(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.triggerCompleted(Uri[] file_urls, String[] file_paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Dazpoet** [comment]
Are you installing mods at the same time as you're updating others? I had this issue doing that but when I split it into first installing and then updating (or vice-versa) it worked.

**Comment by Wolfyharvell** [comment]
Yes, actually. That is what I have been doing. Will try that method for now.

**Comment by MrMiyagiEng** [comment]
I have the same issue however it only does it for smart parts and EVA parachutes mods. It will do it when I try and uninstall them too.

**Comment by politas** [comment]
@MrMiyagiEng , please [log a ticket in the main CKAN repository](https://github.com/KSP-CKAN/CKAN/issues) if you can't find a duplicate there
