### ISSUE TITLE
error when trying to install specific mod

### ISSUE THREAD

**Issue by HagegeR** [KSP-CKAN/NetKAN#4790]
Hi,

this issue is pretty easy to reproduce: filter for compatible mods while in 1.2, try to install GravityTurn Continued, get this error:
```
************** Exception Text **************
CKAN.ModuleNotFoundKraken: Cannot install ContractConfigurator, module not available
   at CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KspVersion ksp_version)
   at CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersion kspversion)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

voila! Hope this is enough :)

**Comment by Olympic1** [comment]
Not getting this issue when installing and installed whitout problems. Are you trying to install `ContractConfigurator` or a mod depending on it.

**Comment by HagegeR** [comment]
well no, maybe it has something to do with the mod I already have installed (inter-compatibility ?)
the error does seem to point in that direction but i can assure you I tried to install GravityTurn Continued

**Comment by HagegeR** [comment]
sorry, had GravityTurn installed of course and this apparently caused a bug when trying to replace another existing mod, fixed it by uninstalling GravityTurn

**Comment by Olympic1** [comment]
Weird that it says that it failed on installing `ContractConfigurator`

**Comment by HagegeR** [comment]
so the real steps are: install gravityTurn (manually since it's not supported in the latest version) and then do all of the above.
really weird indeed.

**Comment by politas** [comment]
Yep, [ModuleNotFoundKraken regularly mentions mods that are unrelated to the actual issue](https://github.com/KSP-CKAN/CKAN/issues/1864). Not sure why.
