### ISSUE TITLE
Exception due to unavailable module

### ISSUE THREAD

**Issue by Elvaron** [KSP-CKAN/NetKAN#4819]
Trying to update Stock Visual Enhancements-High Res from 1:1.1.21 to 2:1.1.4, I get a ModuleNotFoundException stating that KerbalConstructionTime is not available.

I don't think the one mod has any relationship with the other, though I did have KCT installed before it became unavailable for the current KSP version.

As it stands, this keeps SVE from getting installed (Apply changes greyed out).

Exception details:
`************** Exception Text **************
CKAN.ModuleNotFoundKraken: Cannot install KerbalConstructionTime, module not available
   at CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KspVersion ksp_version)
   at CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersion kspversion)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)`

**Comment by politas** [comment]
KSP-CKAN/CKAN#1864 is the ticket for this known issue. Uninstall and reinstall SVE, that should work.

**Comment by Elvaron** [comment]
How would I uninstall it when no Apply changes option appears for it?

**Comment by politas** [comment]
If you aren't getting an "Apply Changes button, then there is a conflict or inconsistency with the current mod set. If you click on the "Installed" header, you can see the selected mods all together. Try deselecting and reselecting mods until you find the combination that clears the issue.
