### ISSUE TITLE
EVA Parachutes & Ejection Seats Updating / Uninstalling V.0.1.6 Fails

### ISSUE THREAD

**Issue by Alexei-B** [KSP-CKAN/NetKAN#4844]
The update from 0.1.6 to 0.1.7 of EVA Parachutes & Ejection Seats causes an exception.
The only operation requested is updating this one mod, nothing else is being updated, and every other update succeeded for every other mod when this update was deselected. I also tried clearing cache, which did not resolve the problem.

CKAN Version: 1.20.1-0-0gd41fe54 (Up-to-date).
### Trace & Message:

```
CKAN.PathErrorKraken: c:/program files (x86)/Steam/SteamApps/common/Kerbal Space Program/GameData/VanguardTechnologies/Parts/EjModule2 is already absolute
   at CKAN.KSPPathUtils.ToAbsolute(String path, String root)
   at CKAN.ModuleInstaller.<AddParentDirectories>c__AnonStorey0.<>m__0(String dir)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at CKAN.ModuleInstaller.AddParentDirectories(HashSet`1 directories)
   at CKAN.ModuleInstaller.Uninstall(String modName)
   at CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove, Boolean enforceConsistency)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, NetAsyncModulesDownloader netAsyncDownloader, Boolean enforceConsistency)
   at CKAN.Main.WasSuccessful(Action action)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by Alexei-B** [comment]
Note: just observed the same exception trying to remove version 0.1.6 of that mod.

**Comment by politas** [comment]
Can you upload your Registry.json file for us? Sounds like there might be something funky in there.

**Comment by Alexei-B** [comment]
I took a look through before hand out of curiosity and didn't notice anything, but then again I wouldn't know precisely what to look for.

[registry.zip](https://github.com/KSP-CKAN/NetKAN/files/559580/registry.zip)

**Comment by politas** [comment]
Try deleting the "GameData\VanguardTechnologies" folder, then running this at a command line:

    ckan.exe remove EVAParachutes

It'll throw a bunch of errors, but it should then stop thinking it has it installed, and you'll be able to install the latest version without further incident. I can't see any reason for it to throw that particular error.

**Comment by Dazpoet** [comment]
Closing this since it seems resolved, feel free to open it again if the error persists.
