### ISSUE TITLE
Enviromental Visual Enhancement can produce CKAN.TooManyModsProvideKraken

### ISSUE THREAD

**Issue by solarsootysmudge** [KSP-CKAN/NetKAN#5357]
Installing Enviromental Visual Enhancement can produce CKAN.TooManyModsProvideKraken.
I can install all of these mods by following a different method. Installing scatter first helps. However I suspect that most end users will do this instead..... 

**1.** Enviromental Visual Enhancements
Asks for config choice
-EVE config
-SVE High
-SVE low
-SVE Medium

**2.** Select SVE High
Asks for sunflare config
-Scatter sunflare
-Astroniki
-Cepheus
-Eden
-SVE sunflare

**3.** Select Astroniki

4. Apply changes
Which lists mods to be installed as

EVE 2EVE1.2-2
SVE Highres 2:1.1.6
scatter 2v0.0300
SVE Scatter config 2:1.1.6
Astroniki for scatter 1.2

**5.** Click on apply
Recommends Planet shine
Tick mod

**6**. Click continue
Throws exception
************** Exception Text **************
CKAN.TooManyModsProvideKraken: Too many mods provide Scatterer-config:
Scatterer-config 2:v0.0300
* SVE-Scatterer-Config 2:1.1.6
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
   at CKAN.ModuleInstaller.InstallList(List`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.WasSuccessful(Action action)
   at CKAN.Main.InstallList(HashSet`1 toInstall, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Further Research.** 
Installing scatter first before going through the steps avoids problems. So I think it is down to Netkan issue related to config files. Thanks for your time.

**Comment by politas** [comment]
This is a code issue. Looks like we aren't staying aware of all the changes as we traverse levels of dependency.Can you re-open this as a main repo [CKAN Issue](https://github.com/KSP-CKAN/CKAN/issues)
