### ISSUE TITLE
NetKAN and CKAN-meta pull request validation is broken

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN#6027]
All NetKAN pull requests are currently failing to validate with errors like these:

```
GitHub pull request #6024 of commit 82ada0ab25919893fe4e2899fc23fa55c7eabb58, no merge conflicts.
Setting status of 82ada0ab25919893fe4e2899fc23fa55c7eabb58 to PENDING with url https://ci.ksp-ckan.org/job/NetKAN/6444/ and message: 'Build started sha1 is merged.'
Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/KSP-CKAN/NetKAN/statuses/82ada0ab25919893fe4e2899fc23fa55c7eabb58
	at org.kohsuke.github.Requester.parse(Requester.java:612)
	at org.kohsuke.github.Requester._to(Requester.java:262)
	at org.kohsuke.github.Requester.to(Requester.java:224)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1000)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:273)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:186)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:132)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:24)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at hudson.model.Run.execute(Run.java:1729)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/KSP-CKAN/NetKAN/statuses/82ada0ab25919893fe4e2899fc23fa55c7eabb58","id":4303105031,"state":"pending","description":"Build started sha1 is merged.","target_url":"https://ci.ksp-ckan.org/job/NetKAN/6444/","context":"default","created_at":"2017-11-07T19:15:41Z","updated_at":"2017-11-07T19:15:41Z","creator":{"login":"netkan-bot","id":10268727,"avatar_url":"https://avatars0.githubusercontent.com/u/10268727?v=4","gravatar_id":"","url":"https://api.github.com/users/netkan-bot","html_url":"https://github.com/netkan-bot","followers_url":"https://api.github.com/users/netkan-bot/followers","following_url":"https://api.github.com/users/netkan-bot/following{/other_user}","gists_url":"https://api.github.com/users/netkan-bot/gists{/gist_id}","starred_url":"https://api.github.com/users/netkan-bot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/netkan-bot/subscriptions","organizations_url":"https://api.github.com/users/netkan-bot/orgs","repos_url":"https://api.github.com/users/netkan-bot/repos","events_url":"https://api.github.com/users/netkan-bot/events{/privacy}","received_events_url":"https://api.github.com/users/netkan-bot/received_events","type":"User","site_admin":false}}
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	... 13 more
```

See #6023 for a specific example and some additional commentary. We're having to test such PRs locally, which means more work for the team and probably slower response times for modders and users.

This may be related to changes in the GitHub API:
https://developer.github.com/changes/2017-10-26-deprecation-reminder-for-certain-github-apps-events-keys-and-routing/

However, the keyword `integration` appears in all of the announced changed events and none of our errors. And response code 201 'Created' sounds like a success status. And the URL in the "failed to deserialize" error does return valid JSON data. It almost looks more like a problem in whatever Java software is handling all this (I can find zero *.java files in all the CKAN/NetKAN/bot source code I have cloned locally).

**Comment by HebaruSan** [comment]
I finally found the test scripts in the xKAN-meta_testing repo, but these errors appear before anything in `build.sh` runs; in fact, according to the log, before it's even _downloaded_. So that would appear to be a dead end.

**Comment by HebaruSan** [comment]
@linuxgurugamer pointed out on IRC that "it actually looks like a JSON error, trying to deserialize an ID which is way too big for an int". This would explain why code that worked fine for a long time (on smaller `id` values) would suddenly fail (if the GitHub API was incrementing the `id` steadily and suddenly crossed over max unsigned int).

But which code is doing that? I still haven't been able to find anything I can patch or submit a pull request against...

**Comment by politas** [comment]
Not just NetKAN PRs - KSP-CKAN/CKAN-meta#1302 has the same issue

**Comment by politas** [comment]
See also #6026

**Comment by techman83** [comment]
Yeah, the API updated, which required a few Jenkins updates. However the ssh agent in the testing container is also busted now! So containers are spinning up and failing to auth, I'll take a further look tonight.

**Comment by techman83** [comment]
And we're back in business. With a container that we can reproduce the environment from!

**Comment by linuxgurugamer** [comment]
Thanks for fixing this
