### ISSUE TITLE
Error while updating MechJeb 2 - DEV RELEASE

### ISSUE THREAD

**Issue by DavidShade** [KSP-CKAN/NetKAN#6292]
Background
----------

**CKAN Version:**  1.24.0

**KSP Version:** 1.3.1

**Operating System:** Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Not since it was last working

**Affected mods and mod versions:**
MechJeb 2 - DEV RELEASE updating from 2.7.0.0-784 to 2.7.0.0-786

Problem
-------

**What steps did you take in CKAN?**
I clicked "Add available updates" and then clicked Apply changes.

**What did you expect to happen?**
I expected the update to install

**What happened instead?**
I receive a null reference exception with this information:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.CkanModule.get_InternetArchiveDownload()
   at CKAN.NetAsyncModulesDownloader.<>c.<DownloadModules>b__8_4(KeyValuePair`2 item)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.NetAsyncModulesDownloader.DownloadModules(NetModuleCache cache, IEnumerable`1 modules)
   at CKAN.ModuleInstaller.DownloadModules(IEnumerable`1 mods, IDownloader downloader)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, IDownloader netAsyncDownloader, Boolean enforceConsistency)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Thanks for the report. This was noted on the forums and fixed in KSP-CKAN/CKAN#2313. In the meantime, the main (i.e., non-"dev") repositories should be unaffected.
