### ISSUE TITLE
Mk3 Stockalike Expansion & Stockalike Mining Extension won't download correctly

### ISSUE THREAD

**Issue by Critter79606** [KSP-CKAN/NetKAN#6855]
Background
----------

**CKAN Version:** 1.24.0

**KSP Version:** 1.5.1

**Operating System:** Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** no

**Affected mods and mod versions:**
Mk3 Stockalike Expansion 1.4.7.3
Stockalike Mining Extension 0.99

Problem
-------

**What steps did you take in CKAN?**
Tried to fresh install Stockalike Mining Extension
Tried to update existing Mk3 Stockalike Expansion
Other mods download correctly.

**What did you expect to happen?**

Mods installed properly

**What happened instead?**
Mining extension - 
Unhandled exception:
CKAN.InvalidModuleFileKraken: C:\Users\rnerovich\AppData\Local\Temp\tmpA70C.tmp has length 6452935, should be 6452920
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncModulesDownloader.<>c__DisplayClass8_0.<DownloadModules>b__3(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.triggerCompleted(Uri[] file_urls, String[] file_paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 

Mk3 - 
Unhandled exception:
CKAN.InvalidModuleFileKraken: C:\Users\rnerovich\AppData\Local\Temp\tmpB83D.tmp has length 20017420, should be 20017396
...(same text)

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
The bot finally caught up.
https://github.com/KSP-CKAN/CKAN-meta/commit/3ffd1af8983fee145ea1ffdef04daeef7b994fb6 
https://github.com/KSP-CKAN/CKAN-meta/commit/9d4697e51910970abbd750f276b3915c0614dd3b
