### ISSUE TITLE
Mk2 Stockalike Expansion download failure

### ISSUE THREAD

**Issue by whiteknight4981** [KSP-CKAN/NetKAN#6990]
Background
----------

**CKAN Version:**
1.25.4

**KSP Version:** 
1.6.1

**Operating System:**
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

**Affected mods and mod versions:**
Mk 2 Stockalike Expansion 2:1.8.3.5

Problem
-------

**What steps did you take in CKAN?**
selected the mod and the tried to download/install

**What did you expect to happen?**
download and install of MOD

**What happened instead?**
CKAN.InvalidModuleFileKraken: Mk2Expansion 2:1.8.3.5: C:\Users\danie\AppData\Local\Temp\tmp6138.tmp has length 29581780, should be 29581777
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)

**Screenshots:**

**CKAN error codes (if applicable):** 
CKAN.InvalidModuleFileKraken: Mk2Expansion 2:1.8.3.5: C:\Users\danie\AppData\Local\Temp\tmp6138.tmp has length 29581780, should be 29581777
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)

**Comment by HebaruSan** [comment]
@techman83 , can you please purge `5D53F15A-netkan-Mk2Expansion.zip` from the bot's cache?

**Comment by HebaruSan** [comment]
Link to monitor it for convenience:

https://github.com/KSP-CKAN/CKAN-meta/commits/master/Mk2Expansion/Mk2Expansion-2-1.8.3.5.ckan

**Comment by HebaruSan** [comment]
Should be fixed now.
https://github.com/KSP-CKAN/CKAN-meta/commit/037bccafa52cf4fb78b910fe045a69b65cfa2bb2
