### ISSUE TITLE
Sarbians Jenkins not working

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/NetKAN#7271]
Problem
-------
@sarbian's Jenkins is not working, see the status page.
This results in an error when trying to inflate netkans of his mods:
`Unexpected character encountered while parsing value: <. Path '', line 7, position 2.`
However, downloading still works fine.

He confirmed it to me in a DM:

>  Hey,  
> It's on my side. I launched a plugin update and it did not restart properly. And now I can not connect to the server until I am back home late tonight...  
> S 

Just opening this issue to let you know and that you don't ask him again :D

**Steps to reproduce**
Inflate a netkan with a kref to sarbians Jenkins.

**Inflation error stack trace (example `CustomBarnKit`):**<details><summary>Click to expand</summary>
```
520 [1] DEBUG CKAN.Net (null) - About to download https://ksp.sarbian.com/jenkins/job/CustomBarnKit/api/json
689 [1] INFO CKAN.Net (null) - Download failed, trying with curlsharp...
690 [1] WARN CKAN.Curl (null) - Curl environment not pre-initialised, performing non-threadsafe init.
700 [1] INFO CKAN.Curl (null) - Using curl-ca bundle: (none)
804 [1] DEBUG CKAN.Net (null) - Download from https://ksp.sarbian.com/jenkins/job/CustomBarnKit/api/json:
<!DOCTYPE html><html><head resURL="/jenkins/static/993225a8" data-rooturl="/jenkins" data-resurl="/jenkins/static/993225a8">
<title>Jenkins</title><link rel="stylesheet" href="/jenkins/static/993225a8/css/layout-common.css" type="text/css" /><link rel="stylesheet" href="/jenkins/static/993225a8/css/style.css" type="text/css" /><link rel="stylesheet" href="/jenkins/static/993225a8/css/color.css" type="text/css" /><link rel="stylesheet" href="/jenkins/static/993225a8/css/responsive-grid.css" type="text/css" /><link rel="shortcut icon" href="/jenkins/static/993225a8/favicon.ico" type="image/vnd.microsoft.icon" /><linkcolor="black" rel="mask-icon" href="/jenkins/images/mask-icon.svg" /><script>var isRunAsTest=false; var rootURL="/jenkins"; var resURL="/jenkins/static/993225a8";</script><script src="/jenkins/static/993225a8/scripts/prototype.js" type="text/javascript"></script><script src="/jenkins/static/993225a8/scripts/behavior.js" type="text/javascript"></script><script src='/jenkins/adjuncts/993225a8/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/jenkins/static/993225a8/scripts/yui/yahoo/yahoo-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/dom/dom-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/event/event-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/animation/animation-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/container/container-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/connection/connection-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/datasource/datasource-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/menu/menu-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/element/element-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/button/button-min.js"></script><script src="/jenkins/static/993225a8/scripts/yui/storage/storage-min.js"></script><script src="/jenkins/static/993225a8/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/jenkins/static/993225a8/scripts/sortable.js" type="text/javascript"></script><link rel="stylesheet" href="/jenkins/static/993225a8/scripts/yui/container/assets/container.css" type="text/css" /><link rel="stylesheet" href="/jenkins/static/993225a8/scripts/yui/assets/skins/sam/skin.css" type="text/css" /><link rel="stylesheet" href="/jenkins/static/993225a8/scripts/yui/container/assets/skins/sam/container.css" type="text/css" /><link rel="stylesheet" href="/jenkins/static/993225a8/scripts/yui/button/assets/skins/sam/button.css" type="text/css" /><link rel="stylesheet" href="/jenkins/static/993225a8/scripts/yui/menu/assets/skins/sam/menu.css" type="text/css" /><link rel="search" href="/jenkins/opensearch.xml" type="application/opensearchdescription+xml" title="Jenkins" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><meta name="viewport" content="width=device-width, initial-scale=1" /><script src="/jenkins/static/993225a8/jsbundles/page-init.js" type="text/javascript"></script></head><body data-model-type="hudson.util.HudsonFailedToLoad" id="jenkins" class="yui-skin-sam two-column jenkins-2.155" data-version="2.155"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/jenkins/"><img src="/jenkins/static/993225a8/images/headshot.png" alt="[Jenkins]" id="jenkins-head-icon" /><img src="/jenkins/static/993225a8/images/title.png" alt="Jenkins" width="139" id="jenkins-name-icon" height="34" /></a></div><div class="login"></div><div class="searchbox hidden-xs"><form role="search" method="get" name="search" style="position:relative;" class="no-json"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input role="searchbox" name="q" placeholder="search" id="search-box" class="has-default-text" /> <a href="https://jenkins.io/redirect/search-box"><img src="/jenkins/static/993225a8/images/16x16/help.png" style="width: 16px; height: 16px; " class="icon-help icon-sm" /></a><div id="search-box-completion"></div><script>createSearchBox("");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav"colspan="2"><link rel='stylesheet' href='/jenkins/adjuncts/993225a8/lib/layout/breadcrumbs.css' type='text/css' /><script src='/jenkins/adjuncts/993225a8/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"><div id="right-top-nav"><div class="smallfont"><a href="?auto_refresh=true">ENABLE AUTO REFRESH</a></div></div></div><ul id="breadcrumbs"></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body" class="clear"><div id="side-panel"></div><div id="main-panel"><a name="skip2content"></a><h1><img src="/jenkins/static/993225a8/images/48x48/error.png" style="width: 48px; height: 48px; " class="icon-error icon-xlg" /> Error</h1><pre>java.lang.IllegalArgumentException: Unable to inject class hudson.model.UserIdMapper
at hudson.init.TaskMethodFinder.lookUp(TaskMethodFinder.java:125)
at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:105)
at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1083)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
at jenkins.model.Jenkins.executeReactor(Jenkins.java:1117)
at jenkins.model.Jenkins.&lt;init>(Jenkins.java:921)
at hudson.model.Hudson.&lt;init>(Hudson.java:85)
at hudson.model.Hudson.&lt;init>(Hudson.java:81)
at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
at hudson.WebAppMain$3.run(WebAppMain.java:250)
</pre></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">Page generated: Jun 28, 2019 1:57:53 PM CEST</span><span class="jenkins_ver"><a href="https://jenkins.io/">Jenkins ver. 2.155</a></span></div></div></div></footer></body></html>
```
</details>

**Comment by DasSkelett** [comment]
It's working again :tada:
