### ISSUE TITLE
SpaceDock serving corrupt zip files

### ISSUE THREAD

**Issue by Shades-McGee** [KSP-CKAN/NetKAN#8590]
Background
----------
* Operating System: Win 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.0.3140

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No.

Problem
-------
**Describe the bug**
While attempting to install the mod 'Near Future Spacecraft 1.4.1', a popup 'Error!' window appears with the following text...

```
CKAN.InvalidModuleFileKraken: NearFutureSpacecraft 1.4.1: C:\Users\First Last\AppData\Local\Temp\tmpA984.tmp is not a valid ZIP file: Error in step EntryData for GameData/NearFutureProps/Props/Plants/PlantPlanters01.dds: CRC mismatch
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
```

... and then the following text appears in the 'Status log' tab in the CKAN window

```
About to install:

 * Near Future Spacecraft 1.4.1 (spacedock.info, 87.0 MiB)
Downloading "https://spacedock.info/mod/708/Near%20Future%20Spacecraft/download/1.4.1"
Trying to install NearFutureSpacecraft 1.4.1, but it's not downloaded or download is corrupted
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

**Steps to reproduce**
* Go to... 'Manage mods' tab in CKAN then select & install 'Near Future Spacecraft'
* See error

**Expected behavior**

I've installed successfully 'Near Future Construction/Electrical/Propulsion/etc.' with no issues.

**Comment by DasSkelett** [comment]
This is probably caused by SpaceDock's flakiness since a few weeks.
Please retry the download when you see this error, maybe after waiting a few minutes. Sorry for the inconvenience :/

**Comment by Shades-McGee** [comment]
Greetings DasSkelett, thank you for replying.  I've retried several times, but I continue to receive the same error.  I'll try again in a few hours and will let you know if the problem persists.

**Comment by DasSkelett** [comment]
It's also still failing for me. But it's definitely not a CKAN problem, the archive is also corrupted when downloading and extracting/checking manually, with e.g. 7zip:
```
$ 7z t Near_Future_Spacecraft-1.4.1.zip 
Scanning the drive for archives:
1 file, 91193997 bytes (87 MiB)

Testing archive: Near_Future_Spacecraft-1.4.1.zip
--
Path = Near_Future_Spacecraft-1.4.1.zip
Type = zip
Physical Size = 91193997

ERROR: CRC Failed : GameData/NearFutureProps/Props/Plants/PlantPlanters01.dds
ERROR: CRC Failed : GameData/NearFutureProps/Props/Tanks/TankGeneric01.dds
ERROR: CRC Failed : GameData/NearFutureProps/Props/Habitation/HabitationProps2.dds
ERROR: Data Error : GameData/NearFutureProps/Props/Seats/KerbalSeat02.dds
ERROR: CRC Failed : GameData/NearFutureProps/Props/Gym/GymProps01.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Parts/FuelTank/service-tank/servicetank-375.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Parts/FuelTank/monoprop-tank/mono-tank-125-1-n.dds
ERROR: Headers Error : GameData/NearFutureSpacecraft/Parts/Engine/landing-engine
ERROR: Headers Error : GameData/NearFutureSpacecraft/Parts/Engine/orbital-engine
ERROR: Headers Error : GameData/NearFutureSpacecraft/Parts/Engine/orbital-engine/orbital-engine-375-1.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Parts/Engine/orbital-engine/orbital-engine-375.mu
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Parts/Command/command-pods/command-pod-375-biconic-1.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Parts/Command/command-pods/mk3-9pod-new.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Parts/Command/command-pods/command-mk4-1.mu
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Spaces/command-375/command-25-iva-window-1.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Spaces/command-375/command-375-biconic-iva-2.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Spaces/mk3-9pod/mk39int_part1-n.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Spaces/command-125/command-125-orbit-iva-1.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Spaces/command-125/command-125-landing-iva-1.dds
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Spaces/command-125/command-125-orbit-iva-1.mu
ERROR: CRC Failed : GameData/NearFutureSpacecraft/Spaces/command-25/command-25-iva-window-1.dds
ERROR: Data Error : GameData/NearFutureSpacecraft/Spaces/command-25/command-25-landing-iva-1.dds

Sub items Errors: 23
Archives with Errors: 1
Sub items Errors: 23
```

And I still believe it's a SpaceDock problem, because this release has been created 6 months ago, we should've gotten a report in the meantime if it was broken all along.

**Comment by HebaruSan** [comment]
Please try reporting SpaceDock's problems on the SpaceDock bug tracker:

- https://github.com/KSP-SpaceDock/SpaceDock/issues

**Comment by Shutch** [comment]
The same corruption bug is also occurring with the following mods:
 * Near Future Aeronautics 2.1.0 (spacedock.info, 38.2 MiB)
 * Near Future Launch Vehicles 2.1.3 (spacedock.info, 161.3 MiB)

**Comment by HebaruSan** [comment]
Please don't post more here. Go to KSP-SpaceDock/SpaceDock#375.
